# Generated by Django 6.0.2 on 2026-03-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recuiter',
            new_name='recruiter',
        ),
    ]
